micronaut:
  application:
    name: productsMnaut
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true
